name: "Actions: Build"

concurrency: build-actions

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build all actions
    runs-on: ubuntu-22.04
    if: ${{ github.repository == 'rumblpak/helm-charts-actions' }}
    steps:
      - name: Get GitHub API token
        id: get-app-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.RUMBLPAK_APP_ID }}
          private_key: ${{ secrets.RUMBLPAK_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ steps.get-app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Collect changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            actions:
              - 'src/**'
              - 'package.json'
              - 'package-lock.json'
              - 'tsconfig.json'

      - name: Build actions
        if: steps.filter.outputs.actions == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          npm ci
          npm run removeNPMAbsolutePaths
          npm run build

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Autobuild from ref: ${{ github.sha }} [ci skip]"
          file_pattern: "package-lock.json package.json node_modules/* lib/*"
          commit_user_name: "rumblpak-bot[bot]"
          commit_user_email: "rumblpak@gmail.com"
          commit_author: "rumblpak@gmail.com"
